### ISSUE TITLE
StarDist extension doesn't work with QuPath 0.6

### ISSUE THREAD

**Issue by ofrag** [qupath/qupath#1635]
Hi,

Thanks for this new exciting version.
I was trying to compare InstaSeg results to StarDist results. InstaSeg is working nicely but the StarDist scripts (from Extensions>StarDist) fail with the following error.
I tried both H&E and Fluorescence scripts. (I set the model path)

```
ERROR: 'org.locationtech.jts.geom.Geometry qupath.lib.roi.GeometryTools.createRectangle(double, double, double, double)'
java.lang.NoSuchMethodError: 'org.locationtech.jts.geom.Geometry qupath.lib.roi.GeometryTools.createRectangle(double, double, double, double)'
    at qupath.ext.stardist.StarDist2D.lambda$detectObjects$10(StarDist2D.java:940)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
    at qupath.ext.stardist.StarDist2D.detectObjects(StarDist2D.java:941)
    at qupath.ext.stardist.StarDist2D.detectObjectsImpl(StarDist2D.java:886)
    at qupath.ext.stardist.StarDist2D.lambda$detectObjects$6(StarDist2D.java:823)
    at qupath.ext.stardist.StarDist2D.runInPool(StarDist2D.java:849)
    at qupath.ext.stardist.StarDist2D.detectObjects(StarDist2D.java:823)
    at qupath.ext.stardist.StarDist2D.detectObjectsImpl(StarDist2D.java:859)
    at qupath.ext.stardist.StarDist2D.lambda$detectObjects$5(StarDist2D.java:812)
    at qupath.ext.stardist.StarDist2D.runInPool(StarDist2D.java:849)
    at qupath.ext.stardist.StarDist2D.detectObjects(StarDist2D.java:812)
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
    at QuPathScript.run(QuPathScript:48)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:331)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:161)
    at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:234)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:1179)
    at qupath.lib.gui.scripting.DefaultScriptEditor$3.run(DefaultScriptEditor.java:1545)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)

```

Best
Ofra

**Comment by alanocallaghan** [comment]
The stardist extension hasn't been updated for QuPath 0.6 yet. I'd suggest one of these three options:

1. Test stardist using QuPath 0.5.1
2. Build the latest stardist extension from source, ideally this branch: https://github.com/qupath/qupath-extension-stardist/pull/36
3. Use the Jar file attached below in QuPath 0.6.0-rc1.

[qupath-extension-stardist-0.6.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16977870/qupath-extension-stardist-0.6.0-SNAPSHOT.zip)

**Comment by petebankhead** [comment]
Thanks @ofrag and @alanocallaghan, I'll close this issue because it's really one for the StartDist extension repo.

We already have an open PR for compatibility at https://github.com/qupath/qupath-extension-stardist/pull/36 and plan to ensure it's compatible when v0.6.0 is finalized.

We're reluctant to do it too early, because then QuPath v0.5.x users might receive notifications to upgrade their extension... and the new one won't be compatible with v0.5, which would cause a new set of problems.

**Comment by ofrag** [comment]
> The stardist extension hasn't been updated for QuPath 0.6 yet. I'd suggest one of these three options:
> 
> 1. Test stardist using QuPath 0.5.1
> 2. Build the latest stardist extension from source, ideally this branch: [Update for QuPath v0.6 qupath-extension-stardist#36](https://github.com/qupath/qupath-extension-stardist/pull/36)
> 3. Use the Jar file attached below in QuPath 0.6.0-rc1.
> 
> [qupath-extension-stardist-0.6.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16977870/qupath-extension-stardist-0.6.0-SNAPSHOT.zip)

Thanks @alanocallaghan 

The new jar solved the issue. 
(QP 0.5.1 is working well with Stardist extension 0.5.0)

best
Ofra
